from __future__ import annotations

# Keywords mapped by category. Energy heuristic is per-keyword.
# "high" = dramatic/fast, "medium" = active, "low" = calm/ambient
CATEGORIES: dict[str, list[tuple[str, str]]] = {
    "city": [
        ("cityscape", "low"),
        ("downtown", "medium"),
        ("traffic", "medium"),
        ("skyline", "low"),
        ("aerial city", "high"),
        ("rush hour", "high"),
        ("highway", "medium"),
        ("intersection", "medium"),
        ("street night", "low"),
        ("urban timelapse", "high"),
        ("subway", "medium"),
        ("bridge", "low"),
    ],
    "tech": [
        ("computer", "low"),
        ("coding", "low"),
        ("server room", "low"),
        ("smartphone", "low"),
        ("circuit board", "low"),
        ("laptop typing", "low"),
        ("programming", "low"),
        ("data center", "low"),
        ("robot", "medium"),
        ("artificial intelligence", "medium"),
        ("3d printing", "medium"),
        ("drone", "high"),
    ],
    "people": [
        ("conversation", "low"),
        ("meeting", "low"),
        ("walking", "medium"),
        ("crowd", "medium"),
        ("handshake", "low"),
        ("interview", "low"),
        ("teamwork", "medium"),
        ("portrait", "low"),
        ("cheering", "high"),
        ("dance", "high"),
        ("audience", "medium"),
        ("commuters", "medium"),
    ],
    "business": [
        ("office", "low"),
        ("workspace", "low"),
        ("presentation", "medium"),
        ("whiteboard", "low"),
        ("conference", "medium"),
        ("startup", "medium"),
        ("coworking", "low"),
        ("brainstorming", "medium"),
        ("desk", "low"),
        ("corporate", "low"),
        ("graph chart", "low"),
        ("handshake deal", "low"),
    ],
    "nature": [
        ("landscape", "low"),
        ("ocean", "medium"),
        ("mountains", "low"),
        ("sunset", "low"),
        ("forest", "low"),
        ("waterfall", "high"),
        ("clouds timelapse", "high"),
        ("rain", "medium"),
        ("snow", "low"),
        ("desert", "low"),
        ("aurora borealis", "low"),
        ("waves crashing", "high"),
    ],
    "food": [
        ("cooking", "medium"),
        ("restaurant", "low"),
        ("coffee", "low"),
        ("kitchen", "medium"),
        ("meal prep", "medium"),
        ("baking", "medium"),
        ("sushi", "low"),
        ("street food", "medium"),
        ("pouring drink", "medium"),
        ("barbecue", "medium"),
        ("fruit", "low"),
        ("plating food", "low"),
    ],
    "lifestyle": [
        ("fitness", "high"),
        ("travel", "medium"),
        ("fashion", "medium"),
        ("luxury", "low"),
        ("nightlife", "high"),
        ("yoga", "low"),
        ("running", "high"),
        ("surfing", "high"),
        ("skateboarding", "high"),
        ("road trip", "medium"),
        ("shopping", "medium"),
        ("spa wellness", "low"),
    ],
    "abstract": [
        ("neon", "high"),
        ("geometric", "low"),
        ("liquid", "medium"),
        ("particles", "high"),
        ("gradient", "low"),
        ("smoke", "medium"),
        ("fire flames", "high"),
        ("bokeh lights", "low"),
        ("ink water", "medium"),
        ("glitch", "high"),
        ("holographic", "medium"),
        ("light rays", "low"),
    ],
}


def all_search_pairs() -> list[tuple[str, str, str]]:
    """Returns (category, keyword, energy) tuples for all searches."""
    pairs = []
    for category, keywords in CATEGORIES.items():
        for keyword, energy in keywords:
            pairs.append((category, keyword, energy))
    return pairs
